name: Deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main  # Trigger deploy on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Using a stable and supported Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive Flask app
      run: |
        zip -r main.zip . -x "*.git*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aitestingdemoebms'  # Replace with your Azure App Service name
        publish-profile: ${{ secrets.SEC_AI }}  # Add your publish profile secret
        package: main.zip
